# coding=utf-8
#If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#Find the sum of all the multiples of 3 or 5 below 1000.

L=[]
for i in range(1,1000):
    if i % 3 == 0 or i % 5 == 0:
        L.append(i)
print sum(L)


sum([x for x in range(1000) if x % 3== 0 or x % 5== 0])

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

L=[]
a,b = 1,1
sum = 0
while b <= 4000000:
    L.append(b)
    a,b = b,a+b
for i in L :
    if i % 2 ==0:
        sum += i
print sum

#The prime factors of 13195 are 5, 7, 13 and 29.
#What is the largest prime factor of the number 600851475143 ?

def largest_prime_factor(s):
    i=2
    while s != 1:
        if s%i == 0:
            s=s/i
            maxprime = i
        else:
            i +=1
    return maxprime
print largest_prime_factor(600851475143)

#A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
#Find the largest palindrome made from the product of two 3-digit numbers.
L=[100*x+10*y+z for x in range(1,10) for y in range(0,10) for z in range(0,10)]
I=[]
for t in L:
    for h in L:
        I.append(t*h)
def reverse(g):
    l=[]
    for i in str(g):
        l.insert(0,i)
    return int(reduce(lambda x,y:x+y,l))
O=[]
for o in I:
    if o == reverse(o):
        O.append(o)
print max(*O)

#smallest mutiple:
#2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
#What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

#my answer
L=range(1,21)
def go_on(l,i):
    for s in l:
        if s%i ==0:
            return True
    return False
i=2
L2=[]
while i!=20:
    if go_on(L,i):
        L2.append(i)
        for s in L:
            if s%i==0:
                L[s-1]=s/i
    else:
        i +=1
print reduce(lambda x,y:x*y,L2)

#referrence
from math import sqrt
my_prime =[n for n in range(2,20) if 0 not in [n%i for i in range(2,int(sqrt(n))+1)]]
result=1
for i in my_prime:
    j=1
    while i**j<=20:
        j+=1
    result=result*i**(j-1)
print result


#problem6
L=[x*x for x in range(1,101)]
re6=0
for x in L:
    re6 +=x
print re6
re7=0
for x in range(1,101):
    re7 +=x
print re7**2
print re7**2-re6

#problem 7
from math import sqrt
def is_prime(x):
    for i in range(2,int(sqrt(x)+1)):
        if x%i==0:
            return False
    return True
i=0
u=2
while i!=10001:
    if is_prime(u):
        i += 1
        u+=1
    else:
        u+=1
print i,u-1

#problem 8
import  re
grid8 = '''73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450'''
L=re.split('\n',grid8)
s=''
for i in L:
    s+=i
H=[]
for i in range(1000-12):
    h = int(s[i])*int(s[i+1])*int(s[i+2])*int(s[i+3])*int(s[i+4])*int(s[i+5])*int(s[i+6])*int(s[i+7])*int(s[i+8])*int(s[i+9])*int(s[i+10])*int(s[i+11])*int(s[i+12])
    H.append(h)
print max(H)

s=''
for i in range(1,13):
    s = s + '*int(s[i+%d])'%i
print s
#problem 9
for x in range(1,1001):
    for y in range(1,1001):
        z=1000-x-y
        if z**2==x**2+y**2:
            print x,y,z
            print x*y*z

#problem 10

from math import sqrt
def is_prime(x): #is_prime(1) True
    for i in range(2,int(sqrt(x)+1)):
        if x%i==0:
            return False
    return True
result10 =0
for i in xrange(2,2000000):
    if is_prime(i):
        result10 +=i
print result10

#problem 11
grid='''08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'''

import re
alist =[re.split(' ',s) for s in re.split('\n',grid)]

H1=[]
for i in range(20):
    for j in range(17):
        H1.append(int(alist[i][j])*int(alist[i][j+1])*int(alist[i][j+2])*int(alist[i][j+3]))
H2=[]
for i in range(17):
    for j in range(20):
        H2.append(int(alist[i][j])*int(alist[i+1][j])*int(alist[i+2][j])*int(alist[i+3][j]))
H3=[]
H4=[]
for i in range(17):
    for j in range(17):
        H3.append(int(alist[i][j])*int(alist[i+1][j+1])*int(alist[i+2][j+2])*int(alist[i+3][j+3]))
        H4.append(int(alist[i+3][j])*int(alist[i+2][j+1])*int(alist[i+1][j+2])*int(alist[i][j+3]))
print max(H1)
print max(H2)
print max(H3)
print max(H4)



#problem 12
def add_n(n):
    return (n+1)*n/2
from math import sqrt
start=0
count = 0
while count <=500:
    count = 1
    start +=1
    for i in range(1,int(sqrt(add_n(start)))+1):
        if not add_n(start)%i:
            count +=2
    if int(sqrt(add_n(start))) == sqrt(add_n(start)):
        count = count - 1
    print count
print count-1,start,add_n(start)

#reference
from math import sqrt
def tri(n):
    return (1 + n) * n / 2

n = 0
counter = 0
while counter <= 500:
    counter = 1
    n += 1
    for i in range(1,int(sqrt(tri(n)))+1):  #从1尝试到int(sqrt(tri(n)))
        if not tri(n) % i:
            counter += 2
    if int(sqrt(tri(n))) == sqrt(tri(n)): #如果
        counter = counter - 1
    print counter
print n,tri(n)


#problem 13
agrid = '''37107287533902102798797998220837590246510135740250

46376937677490009712648124896970078050417018260538

74324986199524741059474233309513058123726617309629

91942213363574161572522430563301811072406154908250

23067588207539346171171980310421047513778063246676

89261670696623633820136378418383684178734361726757

28112879812849979408065481931592621691275889832738

44274228917432520321923589422876796487670272189318

47451445736001306439091167216856844588711603153276

70386486105843025439939619828917593665686757934951

62176457141856560629502157223196586755079324193331

64906352462741904929101432445813822663347944758178

92575867718337217661963751590579239728245598838407

58203565325359399008402633568948830189458628227828

80181199384826282014278194139940567587151170094390

35398664372827112653829987240784473053190104293586

86515506006295864861532075273371959191420517255829

71693888707715466499115593487603532921714970056938

54370070576826684624621495650076471787294438377604

53282654108756828443191190634694037855217779295145

36123272525000296071075082563815656710885258350721

45876576172410976447339110607218265236877223636045

17423706905851860660448207621209813287860733969412

81142660418086830619328460811191061556940512689692

51934325451728388641918047049293215058642563049483

62467221648435076201727918039944693004732956340691

15732444386908125794514089057706229429197107928209

55037687525678773091862540744969844508330393682126

18336384825330154686196124348767681297534375946515

80386287592878490201521685554828717201219257766954

78182833757993103614740356856449095527097864797581

16726320100436897842553539920931837441497806860984

48403098129077791799088218795327364475675590848030

87086987551392711854517078544161852424320693150332

59959406895756536782107074926966537676326235447210

69793950679652694742597709739166693763042633987085

41052684708299085211399427365734116182760315001271

65378607361501080857009149939512557028198746004375

35829035317434717326932123578154982629742552737307

94953759765105305946966067683156574377167401875275

88902802571733229619176668713819931811048770190271

25267680276078003013678680992525463401061632866526

36270218540497705585629946580636237993140746255962

24074486908231174977792365466257246923322810917141

91430288197103288597806669760892938638285025333403

34413065578016127815921815005561868836468420090470

23053081172816430487623791969842487255036638784583

11487696932154902810424020138335124462181441773470

63783299490636259666498587618221225225512486764533

67720186971698544312419572409913959008952310058822

95548255300263520781532296796249481641953868218774

76085327132285723110424803456124867697064507995236

37774242535411291684276865538926205024910326572967

23701913275725675285653248258265463092207058596522

29798860272258331913126375147341994889534765745501

18495701454879288984856827726077713721403798879715

38298203783031473527721580348144513491373226651381

34829543829199918180278916522431027392251122869539

40957953066405232632538044100059654939159879593635

29746152185502371307642255121183693803580388584903

41698116222072977186158236678424689157993532961922

62467957194401269043877107275048102390895523597457

23189706772547915061505504953922979530901129967519

86188088225875314529584099251203829009407770775672

11306739708304724483816533873502340845647058077308

82959174767140363198008187129011875491310547126581

97623331044818386269515456334926366572897563400500

42846280183517070527831839425882145521227251250327

55121603546981200581762165212827652751691296897789

32238195734329339946437501907836945765883352399886

75506164965184775180738168837861091527357929701337

62177842752192623401942399639168044983993173312731

32924185707147349566916674687634660915035914677504

99518671430235219628894890102423325116913619626622

73267460800591547471830798392868535206946944540724

76841822524674417161514036427982273348055556214818

97142617910342598647204516893989422179826088076852

87783646182799346313767754307809363333018982642090

10848802521674670883215120185883543223812876952786

71329612474782464538636993009049310363619763878039

62184073572399794223406235393808339651327408011116

66627891981488087797941876876144230030984490851411

60661826293682836764744779239180335110989069790714

85786944089552990653640447425576083659976645795096

66024396409905389607120198219976047599490197230297

64913982680032973156037120041377903785566085089252

16730939319872750275468906903707539413042652315011

94809377245048795150954100921645863754710598436791

78639167021187492431995700641917969777599028300699

15368713711936614952811305876380278410754449733078

40789923115535562561142322423255033685442488917353

44889911501440648020369068063960672322193204149535

41503128880339536053299340368006977710650566631954

81234880673210146739058568557934581403627822703280

82616570773948327592232845941706525094512325230608

22918802058777319719839450180888072429661980811197

77158542502016545090413245809786882778948721859617

72107838435069186155435662884062257473692284509516

20849603980134001723930671666823555245252804609722

53503534226472524250874054075591789781264330331690'''
import re
s=re.split('\n',agrid)
s1=map(int,s)
outcoming = 0
for i in s1:
    outcoming +=i
print str(outcoming)[:10]


#problem 14

counter_max =0
n_max =0
n_start=1
while n_start<=1000001:
    counter =1
    n = n_start
    while True:
        if not n % 2:
            n=n/2
            counter +=1
            if n ==1:
                break
        if n % 2==1:
            n=3*n+1
            counter +=1
            if n==1:
                break
    print n_start,counter
    if counter_max < counter:
        counter_max = counter
        n_max = n_start
    n_start += 1
print n_max,counter_max


#problem 15
def product(n):
    re=1
    for i in range(1,n+1):
        re = re*i
    return re
print product(40)/product(20)**2

#roblem 16
def re16(x):
    sum = 0
    for i in str(x):
        sum = sum + int(i)
    return sum
print (re16(2**1000))

#problem 17

def count_abc(x):
    d={1:3,2:3,3:5,4:4,5:4,6:2,7:5,8:5,9:4,10:3,11:6,12:6,13:8,14:8,15:7,16:7,17:9,18:8,19:8,20:6,30:6,40:5,50:5,60:5,70:7,80:6,90:6,100:7,'and':3,0:0}
    if x <=20:
        return d[x]
    if x<100:
        return d[int(str(x)[0])*10]+d[int(str(x)[1])]
    if x<1000:
        if x in [100,200,300,400,500,600,700,800,900]:
            return d[int(str(x)[0])]+d[100]
        return d[int(str(x)[0])]+d[100]+d['and']+count_abc(int(str(x)[1]+str(x)[2]))
    if x== 1000:
        return 11
sum = 0
for i in range(1,1001):
    sum = sum + count_abc(i)
print sum

#problem 18
import re
grid18 ='''75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23'''
L1=[map(int,re.split(' ',i)) for i in re.split('\n', grid18)]
n=1
l = 1
L=[]
for i1 in [0,1]:
    for i2 in [0,1]:
        for i3 in [0,1]:
            for i4 in [0,1]:
                for i5 in [0,1]:
                    for i6 in [0,1]:
                        for i7 in [0,1]:
                            for i8 in [0,1]:
                                for i9 in [0,1]:
                                    for i10 in [0,1]:
                                        for i11 in [0,1]:
                                            for i12 in [0,1]:
                                                for i13 in [0,1]:
                                                    for i14 in [0,1]:
                                                        H = [0,
                                                             0+i1,
                                                             0+i1+i2,
                                                             0+i1+i2+i3,
                                                             0+i1+i2+i3+i4,
                                                             0+i1+i2+i3+i4+i5,
                                                             0+i1+i2+i3+i4+i5+i6,
                                                             0+i1+i2+i3+i4+i5+i6+i7,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9+i10,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9+i10+i11,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9+i10+i11+i12,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9+i10+i11+i12+i13,
                                                             0+i1+i2+i3+i4+i5+i6+i7+i8+i9+i10+i11+i12+i13+i14]
                                                        L.append(H)

O=[]
for j in L:
    s = L1[0][j[0]]+L1[1][j[1]]+L1[2][j[2]]+L1[3][j[3]]+L1[4][j[4]]+L1[5][j[5]]+L1[6][j[6]]+L1[7][j[7]]+L1[8][j[8]]+L1[9][j[9]]+L1[10][j[10]]+L1[11][j[11]]+L1[12][j[12]]+L1[13][j[13]]+L1[14][j[14]]
    O.append(s)
print max(O)


#problem 19



def week(date):
    start_date = [1901,1,1]
    start_week = 2
    count = 0
    result = 0
    while start_date != [2000,12,31]:
        count +=1
        start_week = (start_week+1)%7
        if start_date[0]%4 ==0 and start_date[0] !=1900:
            if [start_date[1],start_date[2]] in [[1,31],[2,29],[3,31],[4,30],[5,31],[6,30],[7,31],[8,31],[9,30],[10,31],[11,30]]:
                start_date[1] +=1
                start_date[2] = 1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
            elif [start_date[1],start_date[2]] == [12,31]:
                start_date[0] +=1
                start_date[1] = 1
                start_date[2] = 1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
            else:
                start_date[2] +=1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
        else:
            if [start_date[1],start_date[2]] in [[1,31],[2,28],[3,31],[4,30],[5,31],[6,30],[7,31],[8,31],[9,30],[10,31],[11,30]]:
                start_date[1] +=1
                start_date[2] = 1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
            elif [start_date[1],start_date[2]] == [12,31]:
                start_date[0] +=1
                start_date[1] = 1
                start_date[2] = 1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
            else:
                start_date[2] +=1
                print start_date,count,start_week
                if start_date[2] == 1 and start_week ==0:
                    result +=1
    print count,start_date,start_week,result


#problem 20
def n_product(n):
    s = 1
    for i in range(1,n+1):
        s = s * i
    return s
def sum_123(x):
    s = 0
    for i in str(x):
        s = s + int(i)
    return s
print sum_123(n_product(100))

#problem 21
def amicable(x):
    sum = 0
    for i in range(1,int(x/2)+2):
        if x%i == 0:
            sum += i
    return sum
L=[]
i=1
while i <10000:
    if amicable(amicable(i))==i and amicable(i) != i:
        L.append(i)
    i+=1
result = 0
for i in L:
    result += i
print result

#problem 22
import re
f=open(r'D:\PyCharm\problem archives\names.txt','r')
L=re.split(',',f.read())
L1=[]
for i in L:
    L1.append(i.strip('"'))
L1.sort()
def count_value(name):
    d={'A': 1, 'C': 3, 'B': 2, 'E': 5, 'D': 4, 'G': 7, 'F': 6, 'I': 9, 'H': 8, 'K': 11, 'J': 10, 'M': 13, 'L': 12, 'O': 15, 'N': 14, 'Q': 17, 'P': 16, 'S': 19, 'R': 18, 'U': 21, 'T': 20, 'W': 23, 'V': 22, 'Y': 25, 'X': 24, 'Z': 26}
    sum = 0
    for i in name:
        sum += d[i]
    return sum
order = 0
result22 = 0
for i in L1:
    order += 1
    print order,i
    result22 += order * count_value(i)
print result22

s='abcdefghijklmnopqrstuvwxyz'
d={}
abc = 0
for i in s:
    abc += 1
    d[i.upper()] =abc



#problem 23
def is_true(x):
    sum = 0
    i=1
    while i < int(x/2)+2:
        if x%i == 0:
            sum += i
        i+=1
    if sum > x:
        return True
    return False
def NotAble(x):
    i=1
    while i < int(x/2)+2:
        if is_true(i) and is_true(x-i):
            return False
    return True
sum = 0
for j in range(1,28124):
    if NotAble(j):
        sum += j
        print j,sum
print sum

#problem24
def com(l):
    s=''
    for i in l:
        s+=str(i)
    return int(s)

import itertools
list1=range(10)
iter=itertools.permutations(list1,10)
print map(com,list(iter))
L=map(com,list(iter))
L.sort()
print 'result is',L[999999]

#reference
def perm_cnt(weights):
    l = len(weights)
    return reduce(lambda x,y: x*y, range(1,l+1))  # get l!

def get_ord_of_val_in_perm(weights, value):

    return 100

def nth_perm(weights, order):
    #if type(order)!='int' or type(order)!='long':
    #   return "invalid parameter order"
    #if type(weights)!='str':
    #   return "invalid parameter weights"

    if order > perm_cnt(weights) or order<1:
        return "";

    # generated list of [..., 3!, 2!, 1!]
    facts = map(lambda i: reduce(lambda x,y: x*y, range(1, i+1)), range(1, len(weights)))[::-1]

    s = ''
    q =  n = order
    for i in facts:
        q  = n/i
        n -= q*i  # remainder
        if n==0:  # get biggest value
            q -= 1

        s += weights[q]
        weights = weights[:q]+weights[q+1:]  # weights.remove(q)
        if n==0:
            # s += reduce(lambda x, y: x+y, reversed(weights))
            s += weights[::-1]  # str.reverse()
            break
        elif n==1:
            s += weights
            break
    return s


def perm(weights):
    cnt = perm_cnt(weights)
    # print "perm count " + str(cnt)
    return map(lambda i : nth_perm(weights,i+1), range(cnt))


# print perm("abcd")
print perm("0123")

for i in range(1, 25):
    print nth_perm("0123", i)

print nth_perm("0123456789", 1000000)




#problem 25
x=1
y=1
count=2
while True:
    x,y = y,x+y
    count +=1
    print count,y
    if len(str(y)) ==1000:
        print count,y
        break

#problem 27
from math import sqrt
def is_prime(x):
    if x<=1:
        return False
    elif x==2:
        return True
    else:
        for i in range(2,int(sqrt(x)+2)):
            if x%i == 0:
                return False
        return True
Lb=[]
for i in range(2,1000):
    if is_prime(i):
        Lb.append(i)
max_count = 0
x,y= 0,0
for i in range(-999,1000):
    for j in Lb:
        if is_prime(1+i+j):
            n=0
            count = 0
            while True:
                if is_prime(n**2+i*n+j):
                    count +=1
                else:
                    break
                n +=1
            print count
            if max_count<=count:
                max_count = count
                x=i
                y=j
print x,y,max_count


#problem 31
#1p, 2p, 5p, 10p, 20p, 50p, £1 (100p) and £2 (200p).




















#problem 28
L0=[1]
start = 1
for i in range(2,502):
    for j in range(1,5):
        L0.append(start+j*(2*i-2))
    start += 4*(2*i-2)
print sum(L0)












#problem 29
L=[]
for i in range(2,101):
    for j in range(2,101):
        print i**j
        L.append(i**j)
print len(set(L))










